imas/hackathon

README.md

* slack https://imas-hack.herokuapp.com/
* イベントページ https://imas.connpass.com/event/40290/

README.mdにリンク追加

---

README.md
generate_profile

Add profile generator

---

producers/mazshi.md

add profile - mazshi

---

README.md
archives/20161217-imas_hack.md

アイマスハッカソン2016の成果物まとめ

---

README.md

READMEの更新(slackアイコンの追加)

---

README.md

add event link

---

README.md

add_Kyoto_to_README

---

producers/shy_azusa.md

- プロフィールを追加しました
ご確認，Merge，よろしくお願いいたします!

Add shy_azusa's profile

---

.circleci/config.yml
.gitignore
terraform/Gemfile
terraform/Gemfile.lock
terraform/github/branch_protection.tf
terraform/github/repository_collaborator.tf
terraform/scripts/post_plan_result.rb

`terraform plan` の結果のコメント追加の仕組み化と、
- branch_protection : https://www.terraform.io/docs/providers/github/r/branch_protection.html
- repository_collaborator : https://www.terraform.io/docs/providers/github/r/repository_collaborator.html
のimportを行いました。

Plan結果のPull Requestにコメント

---

.circleci/config.yml
README.md
terraform/github/team_membership.tf

下記を行いました。
- master ci 実行時にプロンプトを出さないように / tfstate ファイルを更新するように
- READMEへのバッジの追加
- 基本コード上で管理するため、team maintainerを一律team memberに(なんか不都合あったらPRください)

Auto approve for terraform

---

plannings/20171210.md

add 20171210 log.

---

terraform/github/membership.tf
terraform/github/team_membership.tf

ごっちP、うろうPをmember,staffへ追加

---

terraform/github/membership.tf
terraform/github/team_membership.tf

- membership で `admin` のメンバーは自動的に team_membership で `maintainer` になっている気がする。
- 新しいメンバーの追加

terraformの記述を調整

---

terraform/github/membership.tf
terraform/github/team_membership.tf

ref. https://imas-hack.slack.com/archives/C1NE6PU9M/p1535944812000100?thread_ts=1535943734.000100&cid=C1NE6PU9M

add kiridaruma to organization.

---

terraform/github/membership.tf
terraform/github/team_membership.tf

自分のアカウントを `membership` と `team_membership` に追加しました
@imas/staff Reviewお願いしたく...!

Add takanakahiko to membership

---

terraform/github/repository.tf
terraform/github/team_membership.tf
terraform/github/team_repository.tf

以下の権限追加お願いします
- imasparqlチームにrdflintの権限を追加
- 私(takemikami)をimasparqlチームに追加

imasparqlチームにrdflintの権限を追加

---

terraform/github/repository_collaborator.tf

- rdflintのadmin権限を私(takemikami)に追加

rdflintリポジトリの管理権限をtakemikamiに追加

---

.circleci/config.yml
terraform/github/repository.tf
terraform/github/repository_collaborator.tf
terraform/github/team.tf
terraform/github/team_repository.tf

add "imasbook" repository

---

terraform/github/membership.tf
terraform/github/repository_collaborator.tf
terraform/github/team_membership.tf

imasbook編集部を反映

---

plannings/20191123.md

Add 20191123

---

producers/tdtds.md

add my profile for the hackathon tomorrow.

add profile of tdtds

---

terraform/github/repository.tf
terraform/github/repository_collaborator.tf
terraform/github/team_repository.tf

githubにrdflint関連のリポジトリ追加をお願いします.
- vscode-rdflint: rdflintのVisual Studio Code用拡張
- 関連Issue: https://github.com/imas/rdflint/issues/81
- 元ソース: https://github.com/takemikami/vscode-rdflint
- homebrew-rdflint: homebrewによるrdflintのインストール定義
- 元ソース: https://github.com/takemikami/homebrew-takemikami

rdflint関連(vscode-rdflint, homebrew-rdflint)のリポジトリ追加

---

terraform/github/repository.tf
terraform/github/repository_collaborator.tf
terraform/github/team_repository.tf

rdflint 関連のリポジトリ追加をお願いします。
- setup-rdflint: rdflint をセットアップする GitHub Action
- 元ソース: https://github.com/foooomio/setup-rdflint

rdflint関連(setup-rdflint)のリポジトリ追加

---

terraform/github/branch_protection.tf

fix imasparql BranchProtection's CI

---

terraform/github/branch_protection.tf

ref. https://github.com/imas/imasparql/pull/359#issuecomment-663629155

Turn off "dismiss_stale_reviews" in imasparql.
